In [8]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

tf.reset_default_graph()

In [9]:
import numpy as np
import os
import matplotlib.pyplot as plt
import pickle

In [10]:
input_train = [[[0],[0],[1],[2],[3]],[[2],[3],[4],[5],[6]],[[3],[4],[5],[6],[7]],[[4],[5],[6],[7],[8]],[[5],[6],[7],[8],[9]]]
output_train_val = [4,7,8,9,10]

output_train = []
for t in range(0,5):
    output_train_k = [0] * 11
    output_train_k[output_train_val[t]] = 1
    output_train.append(output_train_k)

input_train1 = [[[1]]]
output_train1=[1]

input_np1 = np.array(input_train1)
output_np1 = np.array(output_train1)

input_np = np.array(input_train)
output_np = np.array(output_train)

input_train = input_np.reshape(input_np.shape[0],5,input_np.shape[2])
output_train = output_np.reshape(output_np.shape[0],11,)

print(input_train.shape)
print(output_train)

(5, 5, 1)
[[0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1]]


In [11]:
# Training Parameters
learning_rate = 0.001
training_steps = 1000
batch_size = 2
display_step = 200

# Network Parameters
num_input = 1 
timesteps = 5 # timesteps
num_hidden = 128 # hidden layer num of features
num_classes = 11 #  total classes (0-10)

In [12]:
# tf Graph input
X = tf.placeholder("float", [None, timesteps, num_input],name="input")
Y = tf.placeholder("float", [None, num_classes])

# Define weights
weights = {
    'out': tf.Variable(tf.random_normal([num_hidden, num_classes]))
}
biases = {
    'out': tf.Variable(tf.random_normal([num_classes]))
}

In [13]:
def RNN(x, weights, biases):

    # Prepare data shape to match `rnn` function requirements
    # Current data input shape: (batch_size, timesteps, n_input)
    # Required shape: 'timesteps' tensors list of shape (batch_size, n_input)

    # Unstack to get a list of 'timesteps' tensors of shape (batch_size, n_input)
    x = tf.unstack(x, timesteps, 1)

    # Define a lstm cell with tensorflow [supported by tfllte]
    lstm_cell = tf.compat.v1.nn.rnn_cell.BasicLSTMCell(num_hidden, forget_bias=1.0) 

    # Get lstm cell output [supported by tfllte]
    outputs, states = tf.compat.v1.nn.static_rnn(lstm_cell, x, dtype=tf.float32)

    # Linear activation, using rnn inner loop last output
    return tf.matmul(outputs[-1], weights['out']) + biases['out']

In [14]:
logits = RNN(X, weights, biases)
prediction = tf.nn.softmax(logits, name="model_output")

# Define loss and optimizer
loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=logits, labels=Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss_op)

# Evaluate model (with test logits, for dropout to be disabled)
correct_pred = tf.equal(tf.argmax(prediction, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

In [15]:
saver = tf.train.Saver()

In [16]:
# Start training
with tf.Session() as sess:

    # Run the initializer
    sess.run(init)
    
    num_of_batches =  int(len(input_train)/batch_size)
    

    for step in range(1, training_steps+1):
        
        ptr = 0
        
        for j in range(num_of_batches):
            
            batch_x, batch_y = input_train[ptr:ptr+batch_size], output_train[ptr:ptr+batch_size]

            sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
            
            ptr = ptr + batch_size
            
            if (step % display_step == 0) or step == 1:
                # Calculate batch loss and accuracy
                loss, acc = sess.run([loss_op, accuracy], feed_dict={X: input_train,
                                                                     Y: output_train})
                print("Step " + str(step) + ", Minibatch Loss= " + \
                      "{:.4f}".format(loss) + ", Training Accuracy= " + \
                      "{:.3f}".format(acc))

    print("Optimization Finished!")
    
    saver.save(sess, "lstm_model_v1/lstm-model.ckpt")
    
    print("model saved")
    
    tf.train.write_graph(sess.graph.as_graph_def(), '.', 'lstm_model_v1.pbtxt', as_text=True)
    
    print("graph saved")


Step 1, Minibatch Loss= 3.0892, Training Accuracy= 0.200
Step 1, Minibatch Loss= 2.7786, Training Accuracy= 0.400
Step 200, Minibatch Loss= 3.0246, Training Accuracy= 0.800
Step 200, Minibatch Loss= 3.0536, Training Accuracy= 0.800
Step 400, Minibatch Loss= 3.2588, Training Accuracy= 0.800
Step 400, Minibatch Loss= 3.2802, Training Accuracy= 0.800
Step 600, Minibatch Loss= 3.4308, Training Accuracy= 0.800
Step 600, Minibatch Loss= 3.4498, Training Accuracy= 0.800
Step 800, Minibatch Loss= 3.5729, Training Accuracy= 0.800
Step 800, Minibatch Loss= 3.5916, Training Accuracy= 0.800
Step 1000, Minibatch Loss= 3.6992, Training Accuracy= 0.800
Step 1000, Minibatch Loss= 3.7186, Training Accuracy= 0.800
Optimization Finished!
model saved
graph saved


In [17]:
### freezing graph

from tensorflow.python.tools import freeze_graph

freeze_graph.freeze_graph('lstm_model_v1.pbtxt', "", False, 
                          'lstm_model_v1/lstm-model.ckpt', "model_output",
                           "save/restore_all", "save/Const:0",
                           'frozen_lstm_model_v1.pb', True, ""  
                         )

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from lstm_model_v1/lstm-model.ckpt
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 4 variables.
INFO:tensorflow:Converted 4 variables to const ops.


node {
  name: "input"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 5
        }
        dim {
          size: 1
        }
      }
    }
  }
}
node {
  name: "Variable"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 128
          }
          dim {
            size: 11
          }
        }
        tensor_content: "Z\260r\277U\353\377>\001\215\225\276\344R\267>\221\023\251\277\224\372\006?v\252\'?\373Aj>a\323\335\277\356l\373\275^\306\260>z\204\210?C\306w\277\213\244\001\300\027;I?\'\323\351\2763\227\230?\351\013A?\005\372p>\205^l?\037\362\230<\310a\277\277r\270 ?\331\260\342\276\204\340#\277\036G\210\276{\357!@\010\206,\277\024\341S?43\002\300;\213\270\2

In [18]:
### covert to tflite

graph_def_file = "frozen_lstm_model_v1.pb"
input_arrays = ["input"]
output_arrays = ["model_output"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
        graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("converted_lstm_model_v1.tflite", "wb").write(tflite_model)

284856

In [19]:
### doing inference of tflite model

import numpy as np

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="converted_lstm_model_v1.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()


input_data = np.array([[[1],[2],[3],[4],[5]]], dtype=np.float32)

print("input tensor:")
print(input_data)

interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.

output_data = interpreter.get_tensor(output_details[0]['index'])
print("output tensor:")
print(output_data)

print("\nprediction : "+str(np.argmax(output_data)) )

input tensor:
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]]
output tensor:
[[3.2272298e-04 2.9029601e-04 1.2452425e-04 1.3163386e-04 1.5712710e-01
  6.0624639e-05 1.2677746e-04 7.7100331e-01 6.9456041e-02 1.3433212e-03
  1.3674246e-05]]

prediction : 7


In [21]:
# Optimize for inference (removes params used in training not needed for inference)

from tensorflow.python.tools import optimize_for_inference_lib

input_graph_def = tf.GraphDef()
with tf.gfile.Open("frozen_lstm_model_v1.pb", "rb") as f:
    data = f.read()
    input_graph_def.ParseFromString(data)

output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        input_graph_def,
        ["input"], # an array of the input node(s)
        ["model_output"], # an array of output nodes
        tf.float32.as_datatype_enum)


# Save the optimized graph

f = tf.gfile.FastGFile("optimal_lstm_model_v1.pb", "w")
f.write(output_graph_def.SerializeToString())